name: Staging Deploy

# Workflow triggers
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflow jobs
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps to be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node12.x environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
          
      - name: Install Node Modules
        run: npm install
      
      - name: Build Site
        run: npm run build
      
      - name: S3 Bucket Deploy
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with: 
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_STAGING_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_STAGING_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_STAGING_SECRET }}
          AWS_REGION: 'ap-southeast-2'
